### ISSUE TITLE
can-view-import error reporting

### ISSUE THREAD

**Issue by gKreator** [canjs/can-view-import#18]
Seems like anything that crashes in a component that is loaded by can-view-import, has very ambiguous or no error reporting at all.

![image](https://cloud.githubusercontent.com/assets/1431487/21335832/1befa83a-c627-11e6-98e6-ce51f3a003cd.png)

Something like can-compute crashing because of an undefined variable never makes it into the console log.

InValid: ( Nothing in console log... )
![image](https://cloud.githubusercontent.com/assets/1431487/21335865/5522ee14-c627-11e6-836e-034d4322d424.png)

Valid:
![image](https://cloud.githubusercontent.com/assets/1431487/21335874/670260f6-c627-11e6-802a-3b5ce561ec3b.png)

Another example when I am trying to access a property of a purposely undefined variable.
InValid: ( Nothing in console log... )
![image](https://cloud.githubusercontent.com/assets/1431487/21335955/ec817eba-c627-11e6-8b0c-5f163fd31e08.png)

Both scenarios make the <can-import> tag never call isResolved
![image](https://cloud.githubusercontent.com/assets/1431487/21336104/d7cc0c0a-c628-11e6-94cc-9fab4bdcbd74.png)

**Comment by matthewp** [comment]
Logging of errors was handled in https://github.com/canjs/can-view-import/pull/13  Have you tried with 3.0.4?

**Comment by pYr0x** [comment]
i created a github repo https://github.com/pYr0x/donejs-test
i have the same undefined  `var` in the `init` event.
```js
export default Component.extend({
  tag: 'comp-header',
  viewModel: ViewModel,
  view: view,
	events: {
    init: function () {
        console.log("test");
        console.log(this.viewModel.foo.bar);
		}
	}
});
```
i got an error in the console as expected.

![image](https://cloud.githubusercontent.com/assets/1126711/21744700/33299d1e-d51b-11e6-8e80-91e0c4eb8212.png)

close for now, pls reopen if you can proof the bug with the newest can / donejs versions
