### ISSUE TITLE
Using can-tag causes templates to never be rendered

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-view-import#19]
Using code like
```
        <can-import from="place-my-order/restaurant/list/"
            can-tag="pmo-loading">
          <pmo-restaurant-list/>
        </can-import>
```

will cause the `pmo-restaurant-list` component to never be rendered:

![image](https://cloud.githubusercontent.com/assets/5851984/21829780/f433ef34-d75d-11e6-96bd-5588bf80d952.png)

The component is rendered correctly if the `can-tag` is removed: 

![image](https://cloud.githubusercontent.com/assets/5851984/21829793/0e9209e2-d75e-11e6-95dd-722c00e94e57.png)

**Comment by matthewp** [comment]
Has pmo-loading been imported.

**Comment by phillipskevin** [comment]
Yes, it's statically imported above this.

**Comment by phillipskevin** [comment]
The issue here was that the `pmo-loading` component did not have `leakScope: true`, which meant that it was not getting the import promise passed to it from `can-view-import` so it's `<content />` was never shown.

I've udpated the guide to set `leak-scope` on the `<can-component>` for `pmo-loading`.
