### ISSUE TITLE
dynamic import does not work in production

### ISSUE THREAD

**Issue by pYr0x** [canjs/can-view-import#22]
if you have a dynamic import like
```html
<can-import from="foobar/foo">
{{#isResolved}}
<foo/>
{{/isResolved}}
<can-import>
```
and foo.js requires a css or less file, in production it will not work.
see https://github.com/pYr0x/donejs-test/tree/steal-bug

this is because of https://github.com/canjs/can-zone/issues/104
cc @matthewp @phillipskevin

**Comment by matthewp** [comment]
Can you clarify what you mean by "does not work"? Do you mean that it never shows `<foo/>`?

**Comment by pYr0x** [comment]
in the sample app see above, the `comp-header` module will load and log `test` while init https://github.com/pYr0x/donejs-test/blob/steal-bug/assets/comp-header/comp-header.js#L18
but the full page is not loaded 

https://github.com/pYr0x/donejs-test/blob/steal-bug/assets/index.stache doesn't render into the body tag
because this can-zone will fail
https://github.com/donejs/autorender/blob/master/src/template.txt#L115-L142

**Comment by matthewp** [comment]
I still don't totally follow but when I run the example app I'm sure I'll understand better.

**Comment by matthewp** [comment]
Closing, this was fixed in can-zone.
