### ISSUE TITLE
Setup missing badges

### ISSUE THREAD

**Issue by imaustink** [canjs/can-view-import#52]
[![AppVeyor build status](https://ci.appveyor.com/api/projects/status/github/canjs/can-view-import?branch=master&svg=true)](https://ci.appveyor.com/project/matthewp/can-view-import)
[![Coverage status](https://coveralls.io/repos/github/canjs/can-view-import/badge.svg?branch=master)](https://coveralls.io/github/canjs/can-view-import?branch=master)

**Comment by frank-dspeed** [comment]
@imaustink i think this can be closed as badges are added @chasenlehara please review

**Comment by matthewp** [comment]
lgtm
