### ISSUE TITLE
can-dom-data-state dependency

### ISSUE THREAD

**Issue by rob4acre** [canjs/can-view-import#72]
The dependency on can-dom-data-state ^0.1.1 is breaking my builds because version 0.2.0 is loaded by can-util 3.10.15. I get the following error loading steal-stache

Error: You can't have two versions of can-dom-data-state, check your dependencies

**Comment by matthewp** [comment]
Sorry about that, I think someone mistakenly released that package before it was ready. We'll get it fixed asap.

**Comment by rob4acre** [comment]
no prob - i only noticed it because i was setting up a new project. Thanks!

**Comment by andrejewski** [comment]
Fixed by #74
