### ISSUE TITLE
Can't use can-component as a handoff tag for can-tag feature

### ISSUE THREAD

**Issue by matthewp** [canjs/can-view-import#81]

**Comment by matthewp** [comment]
This might be a bug in can-component.

**Comment by justinbmeyer** [comment]
What do you mean?

**Comment by matthewp** [comment]
Failing test is in 8396e8acf5dd5cb78e28f532f153bea7d43e2d3b

Throws here: https://github.com/canjs/can-component/blob/5a04f706c72e90b9d6de2a4985de318a96847e9a/can-component.js#L395

**Comment by matthewp** [comment]
So the difference is that in 3.0, can-component can accept the case where `viewModel` is undefined but cannot in 4.0. So I think the fix is to make it possible in 4.0 as well

**Comment by matthewp** [comment]
Underlying issue: https://github.com/canjs/can-component/issues/183

**Comment by frank-dspeed** [comment]
@matthewp you can close this issue.
