### ISSUE TITLE
Using importPromise throws a false-positive warning

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-view-import#83]
In 3.0, using `state`, `isResolved`, etc gives a warning:

```
WARN: 12: "state" is not in the current scope, so it is being read from the parent scope.
```

this is because the `importPromise` is added as a normal context and is added "above" the normal contexts:

![image](https://user-images.githubusercontent.com/5851984/34063891-b64e7596-e1ba-11e7-9d46-ddd451d78afe.png)

One way to fix this is to make the `importPromise` a `notContext` scope.

This line:
https://github.com/canjs/can-view-import/blob/a7b84b9dc2a4c99523fba495c67f32d190a2c5a2/can-view-import.js#L36

should be:
```
 var scope = tagData.scope.add(importPromise, { notContext: true }); 
```

Using the `importPromise` is working fine with the DoneJS 2.0 pre-release since the `importPromise` is the only scope:

![image](https://user-images.githubusercontent.com/5851984/34063859-7a4efef8-e1ba-11e7-9261-0f82790707ed.png)

**Comment by chasenlehara** [comment]
@Psykoral This should be fixed in [3.2.7](https://github.com/canjs/can-view-import/releases/tag/v3.2.7)

**Comment by Psykoral** [comment]
Very cool, this clears up about 50 warnings! Thanks!

**Comment by justinbmeyer** [comment]
This broke bitballs.  I think it was a breaking change.  But I don't think we should change it back.  Anyone doing bitballs-style routing might find their app broken.
